[package]
name = "htmlstream"
version = "0.1.0"
authors = ["Zongmin Lei <leizongmin@gmail.com>"]

description = "Lightweight HTML parser for rust"
license = "MIT"

[lib]
name = "htmlstream"
path = "src/lib.rs"
